export const demoReports = [
  {
    id: 1001,
    reporterId: null,
    reporterName: "RoadSense AI Detection",
    reporterEmail: "",
    reporterPhone: "",
    issueType: "Pothole",
    severity: "High",
    location: "EM Bypass near Science City, Kolkata",
    description:
      "AI-assisted road scan detected a large pothole in a high-traffic lane. Field verification is pending.",
    latitude: "22.5416",
    longitude: "88.3982",
    imageUrl: "",
    status: "Detected - Not Yet Reported",
    date: "27/08/2026",
    createdAt: "27/08/2026, 09:30:00",
    timeline: [
      {
        status: "Detected - Not Yet Reported",
        note: "RoadSense monitoring system detected a potential road defect.",
        time: "27/08/2026, 09:30:00",
      },
    ],
  },
  {
    id: 1002,
    reporterId: 501,
    reporterName: "Aarav Sen",
    reporterEmail: "aarav@example.com",
    reporterPhone: "9876543210",
    issueType: "Road Crack",
    severity: "Medium",
    location: "Salt Lake Sector V, Kolkata",
    description:
      "Long crack visible across one side of the road near the office area.",
    latitude: "22.5769",
    longitude: "88.4336",
    imageUrl: "",
    status: "Submitted",
    date: "27/08/2026",
    createdAt: "27/08/2026, 10:15:00",
    timeline: [
      {
        status: "Submitted",
        note: "Citizen report received by RoadSense.",
        time: "27/08/2026, 10:15:00",
      },
    ],
  },
  {
    id: 1003,
    reporterId: 502,
    reporterName: "Riya Das",
    reporterEmail: "riya@example.com",
    reporterPhone: "9876543211",
    issueType: "Flooding",
    severity: "High",
    location: "Park Street Crossing, Kolkata",
    description:
      "Heavy waterlogging is affecting vehicle movement and pedestrian safety after rainfall.",
    latitude: "22.5535",
    longitude: "88.3520",
    imageUrl: "",
    status: "In Review",
    date: "26/08/2026",
    createdAt: "26/08/2026, 14:20:00",
    timeline: [
      {
        status: "Submitted",
        note: "Citizen report received by RoadSense.",
        time: "26/08/2026, 14:20:00",
      },
      {
        status: "In Review",
        note: "Authority has started validating the issue and severity.",
        time: "26/08/2026, 16:10:00",
      },
    ],
  },
  {
    id: 1004,
    reporterId: 503,
    reporterName: "Kabir Roy",
    reporterEmail: "kabir@example.com",
    reporterPhone: "9876543212",
    issueType: "Damaged Road Sign",
    severity: "Low",
    location: "Howrah Maidan, Kolkata",
    description:
      "A road direction sign is tilted and difficult for drivers to read.",
    latitude: "22.5958",
    longitude: "88.2636",
    imageUrl: "",
    status: "Awaiting Action",
    date: "26/08/2026",
    createdAt: "26/08/2026, 12:05:00",
    timeline: [
      {
        status: "Submitted",
        note: "Citizen report received by RoadSense.",
        time: "26/08/2026, 12:05:00",
      },
      {
        status: "In Review",
        note: "Issue was verified by the authority.",
        time: "26/08/2026, 14:00:00",
      },
      {
        status: "Awaiting Action",
        note: "Issue is approved but awaiting department action.",
        time: "26/08/2026, 17:00:00",
      },
    ],
  },
  {
    id: 1005,
    reporterId: 504,
    reporterName: "Ishita Paul",
    reporterEmail: "ishita@example.com",
    reporterPhone: "9876543213",
    issueType: "Broken Streetlight",
    severity: "Medium",
    location: "Gariahat Road, Kolkata",
    description:
      "Streetlight near the pedestrian crossing is not working at night.",
    latitude: "22.5196",
    longitude: "88.3659",
    imageUrl: "",
    status: "Assigned",
    date: "25/08/2026",
    createdAt: "25/08/2026, 18:30:00",
    assignedDepartment: "Streetlight Maintenance Department",
    assignedOfficer: "Ward 68 Electrical Team",
    targetDate: "2026-08-30",
    timeline: [
      {
        status: "Submitted",
        note: "Citizen report received by RoadSense.",
        time: "25/08/2026, 18:30:00",
      },
      {
        status: "In Review",
        note: "Authority verified the streetlight malfunction.",
        time: "26/08/2026, 09:00:00",
      },
      {
        status: "Assigned",
        note: "Assigned to Ward 68 Electrical Maintenance Team.",
        time: "26/08/2026, 11:15:00",
      },
    ],
  },
  {
    id: 1006,
    reporterId: 505,
    reporterName: "Soham Ghosh",
    reporterEmail: "soham@example.com",
    reporterPhone: "9876543214",
    issueType: "Pothole",
    severity: "High",
    location: "VIP Road near Airport Gate, Kolkata",
    description:
      "Deep pothole near a busy road junction is causing sudden braking and traffic congestion.",
    latitude: "22.6390",
    longitude: "88.4390",
    imageUrl: "",
    status: "In Progress",
    date: "25/08/2026",
    createdAt: "25/08/2026, 08:40:00",
    assignedDepartment: "Municipal Road Maintenance Unit",
    assignedOfficer: "North Zone Repair Team",
    targetDate: "2026-08-29",
    timeline: [
      {
        status: "Submitted",
        note: "Citizen report received by RoadSense.",
        time: "25/08/2026, 08:40:00",
      },
      {
        status: "In Review",
        note: "Issue classified as high severity.",
        time: "25/08/2026, 10:00:00",
      },
      {
        status: "Assigned",
        note: "North Zone Repair Team assigned.",
        time: "25/08/2026, 12:30:00",
      },
      {
        status: "In Progress",
        note: "Repair crew started pothole filling work.",
        time: "26/08/2026, 08:20:00",
      },
    ],
  },
  {
    id: 1007,
    reporterId: 506,
    reporterName: "Meera Banerjee",
    reporterEmail: "meera@example.com",
    reporterPhone: "9876543215",
    issueType: "Road Crack",
    severity: "Medium",
    location: "New Town Action Area I, Kolkata",
    description:
      "Road surface crack has been repaired and is awaiting field quality verification.",
    latitude: "22.5818",
    longitude: "88.4765",
    imageUrl: "",
    status: "Awaiting Verification",
    date: "24/08/2026",
    createdAt: "24/08/2026, 15:00:00",
    assignedDepartment: "Public Works Department",
    assignedOfficer: "New Town Road Inspection Team",
    targetDate: "2026-08-28",
    timeline: [
      {
        status: "Submitted",
        note: "Citizen report received by RoadSense.",
        time: "24/08/2026, 15:00:00",
      },
      {
        status: "In Progress",
        note: "Surface crack repair activity completed.",
        time: "26/08/2026, 12:00:00",
      },
      {
        status: "Awaiting Verification",
        note: "Repair is awaiting final inspection and verification.",
        time: "27/08/2026, 10:30:00",
      },
    ],
  },
  {
    id: 1008,
    reporterId: 507,
    reporterName: "Ananya Mukherjee",
    reporterEmail: "ananya@example.com",
    reporterPhone: "9876543216",
    issueType: "Flooding",
    severity: "High",
    location: "Tollygunge Metro Area, Kolkata",
    description:
      "Drainage blockage was cleared and road waterlogging has been resolved.",
    latitude: "22.4995",
    longitude: "88.3455",
    imageUrl: "",
    status: "Resolved",
    date: "23/08/2026",
    createdAt: "23/08/2026, 11:10:00",
    assignedDepartment: "Drainage and Flood Control Unit",
    assignedOfficer: "South Zone Drainage Team",
    targetDate: "2026-08-27",
    timeline: [
      {
        status: "Submitted",
        note: "Citizen report received by RoadSense.",
        time: "23/08/2026, 11:10:00",
      },
      {
        status: "Assigned",
        note: "Drainage and Flood Control Unit assigned.",
        time: "24/08/2026, 09:45:00",
      },
      {
        status: "In Progress",
        note: "Drain clearing work started.",
        time: "25/08/2026, 07:30:00",
      },
      {
        status: "Resolved",
        note: "Drainage blockage cleared and road condition restored.",
        time: "27/08/2026, 13:00:00",
      },
    ],
  },
  {
    id: 1009,
    reporterId: 508,
    reporterName: "Rahul Mitra",
    reporterEmail: "rahul@example.com",
    reporterPhone: "9876543217",
    issueType: "Pothole",
    severity: "Low",
    location: "Ballygunge Circular Road, Kolkata",
    description:
      "Duplicate report. Existing report for this pothole is already under maintenance.",
    latitude: "22.5332",
    longitude: "88.3660",
    imageUrl: "",
    status: "Rejected",
    date: "22/08/2026",
    createdAt: "22/08/2026, 16:20:00",
    timeline: [
      {
        status: "Submitted",
        note: "Citizen report received by RoadSense.",
        time: "22/08/2026, 16:20:00",
      },
      {
        status: "Rejected",
        note: "Duplicate report linked to an existing maintenance request.",
        time: "23/08/2026, 10:15:00",
      },
    ],
  },
];